*String concatenation*

*Context:*
1.  *type of print*
2.  *min & mac*
3.  *decimal*
4.  *map & reversed*
5.  *sorted*
6.  *enumerate & zip*
7.  *range*
8.  *set*
9.  *counter*
10.  *dict*
11. *deque*
12. *for*
13. *cycle, repeat & chain*
14. *filterfalse, compress, dropwhile & takewhile*
15. *starmap*
16. *generator*
17. *all & any*
18. *logging*

================================== Importing the required Libraries ===========================

In [36]:
import os
import logging
import cProfile
import numpy as np
from random import randint
from decimal import getcontext, Decimal, localcontext
from collections import Counter, defaultdict, OrderedDict, ChainMap, deque
from itertools import cycle, repeat,chain, filterfalse, compress, dropwhile, takewhile, starmap

In [56]:
data = {
    101: {'name': 'Ali', 'balance': 1000},
    102: {'name': 'Sara', 'balance': 500},
    103: {'name': 'Zohreh', 'balance': 2100},
    104: {'name': 'Babak', 'balance': 600},
    105: {'name': 'Hamid', 'balance': 750},
}
item = data[101]
print(f"{data[101] = }")

print(item['name'], 'has', item['balance'], 'units in their account.')
t=(item['name'], 'has', str(item['balance']), 'units in their account.')
tt='-'.join(t)
print(tt)

data[101] = {'name': 'Ali', 'balance': 1000}
Ali has 1000 units in their account.
Ali-has-1000-units in their account.


In [58]:
data = [{'name': 'A', 'Age':30,  'balance': 1000},
       {'name':  'B', 'Age':25,  'balance': 500},
       {'name':  'C', 'Age':50,  'balance': 2100},
       {'name':  'V', 'Age':20,  'balance': 600},
       {'name':  'R', 'Age':65,  'balance': 750}]
A=max(data, key=lambda dat: dat['balance'])
B=max(data, key=lambda dat: dat['Age'])
print(f"{A = }")
print(f"{B = }")

A = {'name': 'C', 'Age': 50, 'balance': 2100}
B = {'name': 'R', 'Age': 65, 'balance': 750}


In [66]:
getcontext().prec=2                # Context global
print(f"Decimal(1)/Decimal(56): {Decimal(1)/Decimal(56)}")

with localcontext() as c:         # Context local
    c.prec=2
    print(f"Decimal(1)/Decimal(56): {Decimal(1)/Decimal(56)}")

Decimal(1)/Decimal(56): 0.018
Decimal(1)/Decimal(56): 0.018


In [69]:
squ=lambda x: (x, x**2, x**3)
print(f"Square: {squ(5)}")

A=[1,2,3,4]
print(f"map: {list(map(squ, A))}")

A=[1,2,3,4]
B=[1,2,3,4]
squ=list(map(lambda x, y, z: x+y-3*z, A, B, A))
print(f"seq: {squ}")

AA=[3,2,5,4,6,-2,-8,2,5,7]
funcs=[min,max, np.mean,sum,len]
print(f"AA: {list(map(lambda f: f(AA), funcs))}")

print(f"reversed(AA): {list(reversed(AA))}")

Square: (5, 25, 125)
map: [(1, 1, 1), (2, 4, 8), (3, 9, 27), (4, 16, 64)]
seq: [-1, -2, -3, -4]
AA: [-8, 7, 2.4, 24, 10]
reversed(AA): [7, 5, 2, -8, -2, 6, 4, 5, 2, 3]


In [74]:
A=[1,-5,8,0,4,-8,6]
print(f"{A = }")
print(f"{sorted(A) = }")
print(f"{sorted(A, reverse=True) = }")
print(f"{sorted(A, key=np.square, reverse=True) = }")
print(f"{sorted(A, key=lambda x: x**2, reverse=True) = }")
print(f"{sorted(A, key=lambda x: (x%2, x)) = }")  # sorted: First x then x%2

A = [1, -5, 8, 0, 4, -8, 6]
sorted(A) = [-8, -5, 0, 1, 4, 6, 8]
sorted(A, reverse=True) = [8, 6, 4, 1, 0, -5, -8]
sorted(A, key=np.square, reverse=True) = [8, -8, 6, -5, 4, 1, 0]
sorted(A, key=lambda x: x**2, reverse=True) = [8, -8, 6, -5, 4, 1, 0]
sorted(A, key=lambda x: (x%2, x)) = [-8, 0, 4, 6, 8, -5, 1]


In [76]:
A=[1,-5,8,0,4,-8,6]
print(f"{A = }")
for ind, val in enumerate(A):
    print(f"{ind = }    {val = }")

A = [1, 2, 3, 4, 8, 9, 2, -7]
B = [11, 22, 33, 44]
C = 'Python'
for a, b, c in zip(A,B,C):
    print(f"{a,b,c = }")

print(f"zip(A, A[1:], A[2:]):\n {list(zip(A, A[1:], A[2:]))}")

A = [1, -5, 8, 0, 4, -8, 6]
ind = 0    val = 1
ind = 1    val = -5
ind = 2    val = 8
ind = 3    val = 0
ind = 4    val = 4
ind = 5    val = -8
ind = 6    val = 6
 a,b,c = (1, 11, 'P')
 a,b,c = (2, 22, 'y')
 a,b,c = (3, 33, 't')
 a,b,c = (4, 44, 'h')
zip(A, A[1:], A[2:]):
 [(1, 2, 3), (2, 3, 4), (3, 4, 8), (4, 8, 9), (8, 9, 2), (9, 2, -7)]


In [78]:
print(f"{range(10) = }")
print(f"{list(range(10)) = }")
print(f"{list(range(1,10,2)) = }")
print(f"{list(range(20,5,-2)) = }")

range(10) = range(0, 10)
list(range(10)) = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
list(range(1,10,2)) = [1, 3, 5, 7, 9]
list(range(20,5,-2)) = [20, 18, 16, 14, 12, 10, 8, 6]


In [79]:
A=[1,1,5,8,5,2,3,2,3]
print(f"{A = }")
print(f"{set(A) = }")

A = [1, 1, 5, 8, 5, 2, 3, 2, 3]
set(A) = {1, 2, 3, 5, 8}


In [82]:
A = [randint(1,6) for _ in range(15)]
B = Counter(A)
print(f"{A = }")
print(f"Counter: {B}")
print(f"{B.most_common() = }")
print(f"{B.most_common(3) = }")
print(f"{B.most_common()[-1] = }")

C = [randint(1,5) for _ in range(5)]
print(f"{C = }")
B.update(C)
print(f"Counter_update: {B}")
print(f"{B.total() = }")

A = [1, 5, 1, 6, 6, 2, 3, 1, 1, 4, 1, 5, 2, 5, 4]
Counter: Counter({1: 5, 5: 3, 6: 2, 2: 2, 4: 2, 3: 1})
B.most_common() = [(1, 5), (5, 3), (6, 2), (2, 2), (4, 2), (3, 1)]
B.most_common(3) = [(1, 5), (5, 3), (6, 2)]
B.most_common()[-1] = (3, 1)
C = [3, 3, 1, 4, 4]
Counter_update: Counter({1: 6, 4: 4, 5: 3, 3: 3, 6: 2, 2: 2})
B.total() = 20


In [85]:
dic = {'red': 10, 'blue': 20, 'green':0} 
dic = dict(red=10, blue= 20, green=0) 
dic['red']
# dic['black']      # returen error

dic1 = defaultdict(int, dic)
print(f"{dic1 = }")
dic1['black']     # returen 0

dic1_new = OrderedDict(red= 10, blue=20, green=0)
dic1_new.move_to_end('red')
print(f"{dic1_new = }")
print(f"{dic1_new.popitem() = } dic1_new_remove:{dic1_new}")

dic2 = dict(y=15, m=87, c=98)
dic3 = dict(yy=17, mm=7, cc=9)
dic4 = ChainMap(dic2,dic3)
print(f"dic1+dic2: {dic4}")
print(f"dic4.maps: {dic4.maps}")

dic['black']      # returen error

dic1 = defaultdict(<class 'int'>, {'red': 10, 'blue': 20, 'green': 0})
dic1_new = OrderedDict([('blue', 20), ('green', 0), ('red', 10)])
dic1_new.popitem() = ('red', 10) dic1_new_remove:OrderedDict([('blue', 20), ('green', 0)])
dic1+dic2: ChainMap({'y': 15, 'm': 87, 'c': 98}, {'yy': 17, 'mm': 7, 'cc': 9})
dic4.maps: [{'y': 15, 'm': 87, 'c': 98}, {'yy': 17, 'mm': 7, 'cc': 9}]


KeyError: 'black'

In [ ]:
A = deque([1,2,3,4,5,6,3])
print(f"A: {A}")
A.append(10)
print(f"A.append(10):  {A}")
A.appendleft(10)
print(f"A.appendleft(10):  {A}")
A.pop()
print(f"A.pop():  {A}")
A.popleft()
print(f"A.popleft():  {A}")
A.extend([5,6,7])
print(f"A.extend([5,6,7]):  {A}")
A.extendleft([1,4,8])
print(f"A.extendleft([1,4,8]):  {A}")
A.reverse()
print(f"A.reverse():  {A}")
A.rotate(3)
print(f"A.rotate(3):  {A}")    
print(f"A.index(3,4):  {A.index(3,4,8)}")  # Find the first number of 3 between index 4 and 8
print(f"A.count(3):  {A.count(3)}")
A.insert(5,2)                              # Enter number 2 in index 5
print(f"A.insert(5,2):  {A}")
A.remove(2)
print(f"A.remove(2): {A}")

A: deque([1, 2, 3, 4, 5, 6, 3])
A.append(10):  deque([1, 2, 3, 4, 5, 6, 3, 10])
A.appendleft(10):  deque([10, 1, 2, 3, 4, 5, 6, 3, 10])
A.pop():  deque([10, 1, 2, 3, 4, 5, 6, 3])
A.popleft():  deque([1, 2, 3, 4, 5, 6, 3])
A.extend([5,6,7]):  deque([1, 2, 3, 4, 5, 6, 3, 5, 6, 7])
A.extendleft([1,4,8]):  deque([8, 4, 1, 1, 2, 3, 4, 5, 6, 3, 5, 6, 7])
A.reverse():  deque([7, 6, 5, 3, 6, 5, 4, 3, 2, 1, 1, 4, 8])
A.rotate(3):  deque([1, 4, 8, 7, 6, 5, 3, 6, 5, 4, 3, 2, 1])
A.index(3,4):  6
A.count(3):  2
A.insert(5,2):  deque([1, 4, 8, 7, 6, 2, 5, 3, 6, 5, 4, 3, 2, 1])
A.remove(2): deque([1, 4, 8, 7, 6, 5, 3, 6, 5, 4, 3, 2, 1])


In [ ]:
print(f"[x**2 for x in range(1,10): {[x**2 for x in range(1,10)]}")
print(f"[x**2 for x in range(1,10) if x%2]: {[x**2 for x in range(1,10) if x%2]}")
print(f"[x**2 for x in range(1,10) if x%2==0]: {[x**2 for x in range(1,10) if x%2==0]}")
print(f"[(x-1,x,x+1) for x in range(1,10):\n {[(x-1,x,x+1) for x in range(1,10)]}")

A = [1,-1,5,4,1,-2,3,0]
B = {x**2 for x in A}
print(f"B: {B}")
BB = {x:x**2 for x in A}
print(f"BB: {BB}")
BBB = {x:(x**2, x**3) for x in A}
print(f"BBB: {BBB}")

[x**2 for x in range(1,10): [1, 4, 9, 16, 25, 36, 49, 64, 81]
[x**2 for x in range(1,10) if x%2]: [1, 9, 25, 49, 81]
[x**2 for x in range(1,10) if x%2==0]: [4, 16, 36, 64]
[(x-1,x,x+1) for x in range(1,10):
 [(0, 1, 2), (1, 2, 3), (2, 3, 4), (3, 4, 5), (4, 5, 6), (5, 6, 7), (6, 7, 8), (7, 8, 9), (8, 9, 10)]
B: {0, 1, 4, 9, 16, 25}
BB: {1: 1, -1: 1, 5: 25, 4: 16, -2: 4, 3: 9, 0: 0}
BBB: {1: (1, 1), -1: (1, -1), 5: (25, 125), 4: (16, 64), -2: (4, -8), 3: (9, 27), 0: (0, 0)}


In [ ]:
c=cycle('ABCDFRES')
s=cycle(['-',':','.-'])
A=[randint(1,6) for _ in range(10)]
print(f"list(zip(A,c,s)): {list(zip(A,c,s))}")
print(f"repeat(10,3): {list(repeat(10,3))}")
B=np.arange(1,21).reshape(5,4)
print(f"B: {B}")
BB=list(chain(*B))
print(f"BB: {BB}")

list(zip(A,c,s)): [(4, 'A', '-'), (6, 'B', ':'), (5, 'C', '.-'), (4, 'D', '-'), (4, 'F', ':'), (5, 'R', '.-'), (5, 'E', '-'), (3, 'S', ':'), (2, 'A', '.-'), (1, 'B', '-')]
repeat(10,3): [10, 10, 10]
B: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
BB: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [ ]:
A=[2,3,5,8,4,-1,9,10,3,4,-8]
print(f"filter(A>4): {list(filter(lambda x: x>4, A))}")
print(f"filter(A<4): {list(filterfalse(lambda x: x>4, A))}")

B=[True,False,False,True, False,True,True,False,True,False,False]
C=[1,0,0,1,0,1,1,0,1,1,0,1]
print(f"compress(A,B): {list(compress(A,B))}")
print(f"compress(A,C): {list(compress(A,C))}")

print(f"dropwile(A<4): {list(dropwhile(lambda x: x<4, A))}") # The first number of bigger>4 untill end
print(f"takewile(A<4): {list(takewhile(lambda x: x<4, A))}") # From first untill the first number of smaller<4


filter(A>4): [5, 8, 9, 10]
filter(A<4): [2, 3, 4, -1, 3, 4, -8]
compress(A,B): [2, 8, -1, 9, 3]
compress(A,C): [2, 8, -1, 9, 3, 4]
dropwile(A<4): [5, 8, 4, -1, 9, 10, 3, 4, -8]
takewile(A<4): [2, 3]


In [ ]:
A=[(2,5),(1,4),(5,3),(4,2),(3,2)]
print(f"strmap(pow,A): {list(starmap(pow,A))}")
print(f"pow 1: {[pow(x,y) for x,y in A]}")
print(f"pow 2: {[pow(x[0],x[1]) for x in A]}")
print(f"pow 3: {[pow(*x) for x in A]}")

strmap(pow,A): [32, 1, 125, 16, 9]
pow 1: [32, 1, 125, 16, 9]
pow 2: [32, 1, 125, 16, 9]
pow 3: [32, 1, 125, 16, 9]


In [ ]:
print(f" x: {[x**2 for x in range(10)]}")
print(f" x: {(x**2 for x in range(10))}")             # generator
print(f" x: {list(x**2 for x in range(10))}") 
print(f" x: {list(1 for _ in range(10))}")            # generator
A=[1,2,3,4,5]
B=[1,9,7,4,6]
print(f" x, y: {list((x,y) for x,y in zip(A, B))}")   # generator
cProfile.run('list((x,y) for x,y in zip(A, B))')

 x: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
 x: <generator object <genexpr> at 0x00000194B17C1230>
 x: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
 x: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 x, y: [(1, 1), (2, 9), (3, 7), (4, 4), (5, 6)]
         9 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        6    0.000    0.000    0.000    0.000 <string>:1(<genexpr>)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [11]:
A=[1,0,1,-1,0,5,8,7,0]
B=[0,0,0,0]
C=[-1,-1,-2]
print(f"any(A): any(B): any(C):\n {any(A)}   {any(B)}   {any(C)}")  # If a number be ~0-->any:True
print(f"all(A): all(B): all(C):\n {all(A)}   {all(B)}   {all(C)}")  # If all numbers be ~0-->all:True

AA=any([x==10 for x in A])
print(f"any(A(x==10)): {AA}")

AAA=any([x>5 for x in A])
print(f"any(A(x>5)): {AAA}")

AAAA=all([x>5 for x in A])
print(f"all(A(x>5)): {AAAA}")

any(A): any(B): any(C):
 True   False   True
all(A): all(B): all(C):
 False   False   True
any(A(x==10)): False
any(A(x>5)): True
all(A(x>5)): False
